### ISSUE TITLE
[FEAT] - Landing Page should have information about community

### ISSUE THREAD

**Issue by naomi-lgbt** [naomis-novas/homepage#2]
# Feature Request

## Is your feature request related to a problem? Please describe:

As a user, I should visit the home page and see information about our community. This information should include a brief description of the community's goals and purpose, and links to join the community chat (and other platforms?).

## Describe the solution you'd like

This information should go in the `index.html` file, probably.

**Comment by Evavic44** [comment]
I would very much like to contribute to this. 😇 Is there a template design in mind?

**Comment by nhcarrigan** [comment]
This project belongs to the community, so I'm not specifying a template - it's up to you all to decide how you want the site to look 😁

**Comment by Evavic44** [comment]
That means there has to be some sort of meeting with the community members to decide on that, right? 😇  
Oh.. and thanks for adding me to the community.🤸🏾‍♂️

**Comment by nhcarrigan** [comment]
We can discuss it here, or in our [Discord server](http://chat.nhcarrigan.com).

**Comment by Skyhero-admin** [comment]
Even I would like to contribute on this

**Comment by nhcarrigan** [comment]
Pull requests are always welcome - y'all can brainstorm together here, or in our Discord

**Comment by DennaGrey** [comment]
Hey guys, I took a little time today to type up some stuff for the different pages of our website. Its all based on the tabs already made in the nav bar. I also included a form for moderators to fill out for their "cards" on the community tab. 

Any suggestions, edits, comments, welcome! 

**_Home Page:_**
Welcome to The NhCommunity!

We’re a group of members committed to providing a safe, and comfortable space for anyone to try their hand at coding, and have some fun along the way. As our founding member NhCarrigan (link to his tab) is committed to helping members of the freecodecamp community, as well as (any other communities list here) by providing further support to any who need it. We have a staff of moderators who share this vision, come meet them here (link) and check out some of their amazing projects! 

You don’t have to be interested in coding to join us, we often have rounds of fun on Among Us, and talk about a variety of topics. Our moderator team with NhCarrigan, work with the community to set goals and provide projects that everyone can contribute to with help build a sense of community. 

**_Gaming:_**
A love of gaming is something a lot of people share, and we’d love to share it with you! Often playing rounds of Among us, as well as a plethora of other games we are always looking to expand our community of players. 
(Add screenshots of the fun times in among us, list game with shots, an opportunity for everyone to send it fun and funny screenshots of the shenanigans)
(link at the bottom to our calendar) 

_**Discussion:**_
Welcome to our Discussion Center, before joining our community please make sure you’ve read and agreed to our “Rules” (link), if you’re looking for help with a particular freecodecamp problem we have “Resources”(link), and if you have any questions with anything we have a very supportive community that is happy to answer anyquestions in our “Help”(link) section. 

**_Goals&Events_**
Here at the NhCommunity we like to have some fun! We are often working on a handful of projects to improve our community as a whole, that everyone is welcome to contribute to. 

**_Community:_**
Come meet our moderator community and check out all the cool projects they’re working on! 
(List moderator cards below) 


**_Moderator Form:_**
Name: (what do you want us to call you, doesn’t have to be your real name)
_______________________________________
Dev Languages: (already known or are working on) 
	-
	-
	-
	-
Projects: (Any coding projects you’d like to show off)
	-
	-
	-
	-
Servers: (Your servers that you either created or moderate for, besides this one)
	-
	-
Other Projects: (Are you working on improving yourself in other ways? We want to hear about this too!)
	-
	-
	-

**Comment by Vyvy-vi** [comment]
This is awesome!
Maybe we can use nhCommunity instead of NhCommunity??

**Comment by Skyhero-admin** [comment]
Can I try adding some of this info on the page ?

**Comment by DennaGrey** [comment]
> This is awesome!
> Maybe we can use nhCommunity instead of NhCommunity??

Yeah that's fine by me :)



> Can I try adding some of this info on the page that I am trying to make ?

Absolutely!

**Comment by Evavic44** [comment]
> Hey guys, I took a little time today to type up some stuff for the different pages of our website. Its all based on the tabs already made in the nav bar. I also included a form for moderators to fill out for their "cards" on the community tab. 
> 
> Any suggestions, edits, comments, welcome! 
> 
> **_Home Page:_**
> Welcome to The nhCommunity!
> 
> We’re a group of members committed to providing a safe, and comfortable space for anyone to try their hand at coding, and have some fun along the way. As our founding member NhCarrigan (link to his tab) is committed to helping members of the freecodecamp community, as well as (any other communities list here) by providing further support to any who need it. We have a staff of moderators who share this vision, come meet them here (link) and check out some of their amazing projects! 
> 
> You don’t have to be interested in coding to join us, we often have rounds of fun on Among Us, and talk about a variety of topics. Our moderator team with NhCarrigan, work with the community to set goals and provide projects that everyone can contribute to, in order to help build a sense of community. 
> 
> **_Gaming:_**
> A love of gaming is something a lot of people share, and we’d love to share it with you! Often playing rounds of Among us, as well as a plethora of other games we are always looking to expand our community of players. 
> (Add screenshots of the fun times in among us, list game with shots, an opportunity for everyone to send it fun and funny screenshots of the shenanigans)
> (link at the bottom to our calendar) 
> 
> _**Discussion:**_
> Welcome to our Discussion Center, before joining our community please make sure you’ve read and agreed to our “Rules” (link), if you’re looking for help with a particular freecodecamp problem we have “Resources”(link), and if you have any questions with anything we have a very supportive community that is happy to answer anyquestions in our “Help”(link) section. 
> 
> **_Goals&Events_**
> Here at the NhCommunity we like to have some fun! We are often working on a handful of projects to improve our community as a whole, that everyone is welcome to contribute to. 
> 
> **_Community:_**
> Come meet our moderator community and check out all the cool projects they’re working on! 
> (List moderator cards below) 
> 
> 
> **_Moderator Form:_**
> Name: (what do you want us to call you, doesn’t have to be your real name)
> _______________________________________
> Dev Languages: (already known or are working on) 
> 	-
> 	-
> 	-
> 	-
> Projects: (Any coding projects you’d like to show off)
> 	-
> 	-
> 	-
> 	-
> Servers: (Your servers that you either created or moderate for, besides this one)
> 	-
> 	-
> Other Projects: (Are you working on improving yourself in other ways? We want to hear about this too!)
> 	-
> 	-
> 	-
> *edited for grammar and spelling errors. 

This is great. Will try to work on a section. 🙂👍

**Comment by Evavic44** [comment]
Good morning everyone. I just styled the gaming section, are we merging @Skyhero-admin PR so we can move forward with the website? 😇

**Comment by thuongtruong1009** [comment]
After visiting your community site, I have a few suggestions:
1. In the header, You should add the logo image to them. At the same time when scrolling down, the border-bottom of the header should be removed.
2. You can use the jQuery library to create text effects at the line "Welcome to Carrigan's Community! 🔥"
3. In the footer, you should add the copyright and set their background color to distinguish it from the body
--> Hope they will help you. Thanks very much!
