### ISSUE TITLE
[BUG] Missing Images

### ISSUE THREAD

**Issue by lucifertrj** [naomis-novas/homepage#62]
### What bug did you encounter?

``Timiro`` from Community Manager has a missing image/icon.

``RavenclawFander`` from Moderator Team has a missing image/icon.

### What did you expect to happen?

It should be replace with icon or image

**Comment by shubhamsigdar1** [comment]
can you please add Timiro image on a file

**Comment by kelvinparmar** [comment]
I would like to work on that issue @naomi-lgbt 
please give me reply for that
