### ISSUE TITLE
[FEAT] Make join community button on website more dynamic and fix padding.

### ISSUE THREAD

**Issue by KaKashi1210** [naomis-novas/homepage#69]
### What feature would you like to see?

![image](https://user-images.githubusercontent.com/97914006/219958724-050ec6f5-af01-4cdf-9fe8-5a0d8b52447a.png)
The Join Button on website does not have proper padding and it doesnt have any effect when user hovers over it, adding basic hover effect in CSS might do the work.

**Comment by naomi-lgbt** [comment]
Sure, I'd be happy to see what folks can come up with for improving the button styling~!
